"""add phone number

Revision ID: 648693c14662
Revises: cc686cca67c8
Create Date: 2022-11-04 15:07:06.585492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648693c14662'
down_revision = 'cc686cca67c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
